export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const SET_PRICES = 'SET_PRICES';

export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
export const RESET_ORDER = 'RESET_ORDER';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCESS = 'FETCH_ORDERS_SUCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCESS = 'AUTH_SUCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
